# crea una imagen de nombre    : dockerizingdjango_web
#

FROM python:2.7
MAINTAINER Franz A. Lopez Choque
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
ADD . /code/
RUN pip install --no-cache-dir -r requirements.txt
WORKDIR /code/
RUN chmod ug+x run.sh
